# fly.toml app configuration file generated for reactivities-777 on 2024-02-24T12:10:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivities-777'
primary_region = 'ams'

[build]
  image = 'ihorarkh/reactivities:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dizjnefoe"
  Cloudinary__ApiKey="219726925225685"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
